import { useState } from 'react'

// A student typing "I can't read the board and need things read to me" is producing what
// functions as special-education record data. They are entitled to know where it goes,
// in language they can actually read. Stating the boundary plainly is also the honest
// answer to the FERPA/COPPA question — but only if it's stated.

function PrivacyNote({ variant = 'inline' }) {
  const [open, setOpen] = useState(false)

  return (
    <div
      className={
        variant === 'card'
          ? 'w-full max-w-md rounded-2xl border border-ink/10 bg-white/50 px-5 py-4'
          : 'w-full'
      }
    >
      <button
        type="button"
        onClick={() => setOpen(!open)}
        aria-expanded={open}
        className="flex items-center gap-2 text-sm text-muted hover:text-harbor transition
          focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-harbor/40 rounded"
      >
        <span aria-hidden="true">🔒</span>
        Who can see what I write here?
        <span aria-hidden="true" className="text-xs">{open ? '▲' : '▼'}</span>
      </button>

      {open && (
        <div className="mt-3 flex flex-col gap-2 text-sm text-ink/80 animate-fadeIn">
          <p>
            <strong className="font-medium">Nobody at your school, unless you show them.</strong> Your
            reflections are saved only in this browser, on this device. There's no account, no
            login, and no MyVoice database — we never receive them.
          </p>
          <p>
            To write your explanations and roleplay the teacher, what you type is sent to
            Anthropic's Claude, and read-aloud audio may be generated by ElevenLabs. They process
            it to answer and don't use it to train their models.
          </p>
          <p>
            Your one-pager is only shared when <em>you</em> copy or print it and hand it to
            someone. Clearing your browser data erases your reflections permanently — including
            from us, because we never had them.
          </p>
          <p className="text-muted">
            Because reflections live only in this browser, they won't follow you to another
            device or survive a school device being wiped.
          </p>
        </div>
      )}
    </div>
  )
}

export default PrivacyNote
